/*
Sumo Logic API

YOLO! 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SearchJobMessagesMapMap struct for SearchJobMessagesMapMap
type SearchJobMessagesMapMap struct {
	Receipttime *string `json:"_receipttime,omitempty"`
	Source *string `json:"_source,omitempty"`
	Collector *string `json:"_collector,omitempty"`
	Format *string `json:"_format,omitempty"`
	Blockid *string `json:"_blockid,omitempty"`
	Messageid *string `json:"_messageid,omitempty"`
	Messagetime *string `json:"_messagetime,omitempty"`
	Collectorid *string `json:"_collectorid,omitempty"`
	Sourcename *string `json:"_sourcename,omitempty"`
	Sourcehost *string `json:"_sourcehost,omitempty"`
	Raw *string `json:"_raw,omitempty"`
	Size *string `json:"_size,omitempty"`
	Sourcecategory *string `json:"_sourcecategory,omitempty"`
	Sourceid *string `json:"_sourceid,omitempty"`
	Messagecount *string `json:"_messagecount,omitempty"`
}

// NewSearchJobMessagesMapMap instantiates a new SearchJobMessagesMapMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchJobMessagesMapMap() *SearchJobMessagesMapMap {
	this := SearchJobMessagesMapMap{}
	return &this
}

// NewSearchJobMessagesMapMapWithDefaults instantiates a new SearchJobMessagesMapMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchJobMessagesMapMapWithDefaults() *SearchJobMessagesMapMap {
	this := SearchJobMessagesMapMap{}
	return &this
}

// GetReceipttime returns the Receipttime field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetReceipttime() string {
	if o == nil || o.Receipttime == nil {
		var ret string
		return ret
	}
	return *o.Receipttime
}

// GetReceipttimeOk returns a tuple with the Receipttime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetReceipttimeOk() (*string, bool) {
	if o == nil || o.Receipttime == nil {
		return nil, false
	}
	return o.Receipttime, true
}

// HasReceipttime returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasReceipttime() bool {
	if o != nil && o.Receipttime != nil {
		return true
	}

	return false
}

// SetReceipttime gets a reference to the given string and assigns it to the Receipttime field.
func (o *SearchJobMessagesMapMap) SetReceipttime(v string) {
	o.Receipttime = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *SearchJobMessagesMapMap) SetSource(v string) {
	o.Source = &v
}

// GetCollector returns the Collector field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetCollector() string {
	if o == nil || o.Collector == nil {
		var ret string
		return ret
	}
	return *o.Collector
}

// GetCollectorOk returns a tuple with the Collector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetCollectorOk() (*string, bool) {
	if o == nil || o.Collector == nil {
		return nil, false
	}
	return o.Collector, true
}

// HasCollector returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasCollector() bool {
	if o != nil && o.Collector != nil {
		return true
	}

	return false
}

// SetCollector gets a reference to the given string and assigns it to the Collector field.
func (o *SearchJobMessagesMapMap) SetCollector(v string) {
	o.Collector = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetFormat() string {
	if o == nil || o.Format == nil {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetFormatOk() (*string, bool) {
	if o == nil || o.Format == nil {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasFormat() bool {
	if o != nil && o.Format != nil {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *SearchJobMessagesMapMap) SetFormat(v string) {
	o.Format = &v
}

// GetBlockid returns the Blockid field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetBlockid() string {
	if o == nil || o.Blockid == nil {
		var ret string
		return ret
	}
	return *o.Blockid
}

// GetBlockidOk returns a tuple with the Blockid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetBlockidOk() (*string, bool) {
	if o == nil || o.Blockid == nil {
		return nil, false
	}
	return o.Blockid, true
}

// HasBlockid returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasBlockid() bool {
	if o != nil && o.Blockid != nil {
		return true
	}

	return false
}

// SetBlockid gets a reference to the given string and assigns it to the Blockid field.
func (o *SearchJobMessagesMapMap) SetBlockid(v string) {
	o.Blockid = &v
}

// GetMessageid returns the Messageid field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetMessageid() string {
	if o == nil || o.Messageid == nil {
		var ret string
		return ret
	}
	return *o.Messageid
}

// GetMessageidOk returns a tuple with the Messageid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetMessageidOk() (*string, bool) {
	if o == nil || o.Messageid == nil {
		return nil, false
	}
	return o.Messageid, true
}

// HasMessageid returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasMessageid() bool {
	if o != nil && o.Messageid != nil {
		return true
	}

	return false
}

// SetMessageid gets a reference to the given string and assigns it to the Messageid field.
func (o *SearchJobMessagesMapMap) SetMessageid(v string) {
	o.Messageid = &v
}

// GetMessagetime returns the Messagetime field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetMessagetime() string {
	if o == nil || o.Messagetime == nil {
		var ret string
		return ret
	}
	return *o.Messagetime
}

// GetMessagetimeOk returns a tuple with the Messagetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetMessagetimeOk() (*string, bool) {
	if o == nil || o.Messagetime == nil {
		return nil, false
	}
	return o.Messagetime, true
}

// HasMessagetime returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasMessagetime() bool {
	if o != nil && o.Messagetime != nil {
		return true
	}

	return false
}

// SetMessagetime gets a reference to the given string and assigns it to the Messagetime field.
func (o *SearchJobMessagesMapMap) SetMessagetime(v string) {
	o.Messagetime = &v
}

// GetCollectorid returns the Collectorid field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetCollectorid() string {
	if o == nil || o.Collectorid == nil {
		var ret string
		return ret
	}
	return *o.Collectorid
}

// GetCollectoridOk returns a tuple with the Collectorid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetCollectoridOk() (*string, bool) {
	if o == nil || o.Collectorid == nil {
		return nil, false
	}
	return o.Collectorid, true
}

// HasCollectorid returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasCollectorid() bool {
	if o != nil && o.Collectorid != nil {
		return true
	}

	return false
}

// SetCollectorid gets a reference to the given string and assigns it to the Collectorid field.
func (o *SearchJobMessagesMapMap) SetCollectorid(v string) {
	o.Collectorid = &v
}

// GetSourcename returns the Sourcename field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetSourcename() string {
	if o == nil || o.Sourcename == nil {
		var ret string
		return ret
	}
	return *o.Sourcename
}

// GetSourcenameOk returns a tuple with the Sourcename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetSourcenameOk() (*string, bool) {
	if o == nil || o.Sourcename == nil {
		return nil, false
	}
	return o.Sourcename, true
}

// HasSourcename returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasSourcename() bool {
	if o != nil && o.Sourcename != nil {
		return true
	}

	return false
}

// SetSourcename gets a reference to the given string and assigns it to the Sourcename field.
func (o *SearchJobMessagesMapMap) SetSourcename(v string) {
	o.Sourcename = &v
}

// GetSourcehost returns the Sourcehost field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetSourcehost() string {
	if o == nil || o.Sourcehost == nil {
		var ret string
		return ret
	}
	return *o.Sourcehost
}

// GetSourcehostOk returns a tuple with the Sourcehost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetSourcehostOk() (*string, bool) {
	if o == nil || o.Sourcehost == nil {
		return nil, false
	}
	return o.Sourcehost, true
}

// HasSourcehost returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasSourcehost() bool {
	if o != nil && o.Sourcehost != nil {
		return true
	}

	return false
}

// SetSourcehost gets a reference to the given string and assigns it to the Sourcehost field.
func (o *SearchJobMessagesMapMap) SetSourcehost(v string) {
	o.Sourcehost = &v
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetRaw() string {
	if o == nil || o.Raw == nil {
		var ret string
		return ret
	}
	return *o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetRawOk() (*string, bool) {
	if o == nil || o.Raw == nil {
		return nil, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasRaw() bool {
	if o != nil && o.Raw != nil {
		return true
	}

	return false
}

// SetRaw gets a reference to the given string and assigns it to the Raw field.
func (o *SearchJobMessagesMapMap) SetRaw(v string) {
	o.Raw = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetSize() string {
	if o == nil || o.Size == nil {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetSizeOk() (*string, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *SearchJobMessagesMapMap) SetSize(v string) {
	o.Size = &v
}

// GetSourcecategory returns the Sourcecategory field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetSourcecategory() string {
	if o == nil || o.Sourcecategory == nil {
		var ret string
		return ret
	}
	return *o.Sourcecategory
}

// GetSourcecategoryOk returns a tuple with the Sourcecategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetSourcecategoryOk() (*string, bool) {
	if o == nil || o.Sourcecategory == nil {
		return nil, false
	}
	return o.Sourcecategory, true
}

// HasSourcecategory returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasSourcecategory() bool {
	if o != nil && o.Sourcecategory != nil {
		return true
	}

	return false
}

// SetSourcecategory gets a reference to the given string and assigns it to the Sourcecategory field.
func (o *SearchJobMessagesMapMap) SetSourcecategory(v string) {
	o.Sourcecategory = &v
}

// GetSourceid returns the Sourceid field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetSourceid() string {
	if o == nil || o.Sourceid == nil {
		var ret string
		return ret
	}
	return *o.Sourceid
}

// GetSourceidOk returns a tuple with the Sourceid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetSourceidOk() (*string, bool) {
	if o == nil || o.Sourceid == nil {
		return nil, false
	}
	return o.Sourceid, true
}

// HasSourceid returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasSourceid() bool {
	if o != nil && o.Sourceid != nil {
		return true
	}

	return false
}

// SetSourceid gets a reference to the given string and assigns it to the Sourceid field.
func (o *SearchJobMessagesMapMap) SetSourceid(v string) {
	o.Sourceid = &v
}

// GetMessagecount returns the Messagecount field value if set, zero value otherwise.
func (o *SearchJobMessagesMapMap) GetMessagecount() string {
	if o == nil || o.Messagecount == nil {
		var ret string
		return ret
	}
	return *o.Messagecount
}

// GetMessagecountOk returns a tuple with the Messagecount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMapMap) GetMessagecountOk() (*string, bool) {
	if o == nil || o.Messagecount == nil {
		return nil, false
	}
	return o.Messagecount, true
}

// HasMessagecount returns a boolean if a field has been set.
func (o *SearchJobMessagesMapMap) HasMessagecount() bool {
	if o != nil && o.Messagecount != nil {
		return true
	}

	return false
}

// SetMessagecount gets a reference to the given string and assigns it to the Messagecount field.
func (o *SearchJobMessagesMapMap) SetMessagecount(v string) {
	o.Messagecount = &v
}

func (o SearchJobMessagesMapMap) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Receipttime != nil {
		toSerialize["_receipttime"] = o.Receipttime
	}
	if o.Source != nil {
		toSerialize["_source"] = o.Source
	}
	if o.Collector != nil {
		toSerialize["_collector"] = o.Collector
	}
	if o.Format != nil {
		toSerialize["_format"] = o.Format
	}
	if o.Blockid != nil {
		toSerialize["_blockid"] = o.Blockid
	}
	if o.Messageid != nil {
		toSerialize["_messageid"] = o.Messageid
	}
	if o.Messagetime != nil {
		toSerialize["_messagetime"] = o.Messagetime
	}
	if o.Collectorid != nil {
		toSerialize["_collectorid"] = o.Collectorid
	}
	if o.Sourcename != nil {
		toSerialize["_sourcename"] = o.Sourcename
	}
	if o.Sourcehost != nil {
		toSerialize["_sourcehost"] = o.Sourcehost
	}
	if o.Raw != nil {
		toSerialize["_raw"] = o.Raw
	}
	if o.Size != nil {
		toSerialize["_size"] = o.Size
	}
	if o.Sourcecategory != nil {
		toSerialize["_sourcecategory"] = o.Sourcecategory
	}
	if o.Sourceid != nil {
		toSerialize["_sourceid"] = o.Sourceid
	}
	if o.Messagecount != nil {
		toSerialize["_messagecount"] = o.Messagecount
	}
	return json.Marshal(toSerialize)
}

type NullableSearchJobMessagesMapMap struct {
	value *SearchJobMessagesMapMap
	isSet bool
}

func (v NullableSearchJobMessagesMapMap) Get() *SearchJobMessagesMapMap {
	return v.value
}

func (v *NullableSearchJobMessagesMapMap) Set(val *SearchJobMessagesMapMap) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchJobMessagesMapMap) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchJobMessagesMapMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchJobMessagesMapMap(val *SearchJobMessagesMapMap) *NullableSearchJobMessagesMapMap {
	return &NullableSearchJobMessagesMapMap{value: val, isSet: true}
}

func (v NullableSearchJobMessagesMapMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchJobMessagesMapMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


