/*
Sumo Logic API

YOLO! 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SearchJobMessagesMap struct for SearchJobMessagesMap
type SearchJobMessagesMap struct {
	Map *SearchJobMessagesMapMap `json:"map,omitempty"`
}

// NewSearchJobMessagesMap instantiates a new SearchJobMessagesMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchJobMessagesMap() *SearchJobMessagesMap {
	this := SearchJobMessagesMap{}
	return &this
}

// NewSearchJobMessagesMapWithDefaults instantiates a new SearchJobMessagesMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchJobMessagesMapWithDefaults() *SearchJobMessagesMap {
	this := SearchJobMessagesMap{}
	return &this
}

// GetMap returns the Map field value if set, zero value otherwise.
func (o *SearchJobMessagesMap) GetMap() SearchJobMessagesMapMap {
	if o == nil || o.Map == nil {
		var ret SearchJobMessagesMapMap
		return ret
	}
	return *o.Map
}

// GetMapOk returns a tuple with the Map field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchJobMessagesMap) GetMapOk() (*SearchJobMessagesMapMap, bool) {
	if o == nil || o.Map == nil {
		return nil, false
	}
	return o.Map, true
}

// HasMap returns a boolean if a field has been set.
func (o *SearchJobMessagesMap) HasMap() bool {
	if o != nil && o.Map != nil {
		return true
	}

	return false
}

// SetMap gets a reference to the given SearchJobMessagesMapMap and assigns it to the Map field.
func (o *SearchJobMessagesMap) SetMap(v SearchJobMessagesMapMap) {
	o.Map = &v
}

func (o SearchJobMessagesMap) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Map != nil {
		toSerialize["map"] = o.Map
	}
	return json.Marshal(toSerialize)
}

type NullableSearchJobMessagesMap struct {
	value *SearchJobMessagesMap
	isSet bool
}

func (v NullableSearchJobMessagesMap) Get() *SearchJobMessagesMap {
	return v.value
}

func (v *NullableSearchJobMessagesMap) Set(val *SearchJobMessagesMap) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchJobMessagesMap) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchJobMessagesMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchJobMessagesMap(val *SearchJobMessagesMap) *NullableSearchJobMessagesMap {
	return &NullableSearchJobMessagesMap{value: val, isSet: true}
}

func (v NullableSearchJobMessagesMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchJobMessagesMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


